apiVersion: v1
kind: Pod
metadata:
  name: nginx-nfs
  namespace: default
spec:
  containers:
  - name: nginx-nfs
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  nodeSelector:
    share-test: "all"
  volumes:
  - name: test
    flexVolume:
      driver: "kuberlab/share"
      fsType: "share"
      secretRef:
        name: test-aws
      options:
        bucket: "test-k-aws"
        kuberlabFS: "s3"
        url: "https://github.com/dreyk/s3share"